/** 緯度・経度の座標点 */
export type GeoPoint = {
  latitude: number;
  longitude: number;
};

/** スコアリングゾーンの形状タイプ */
export type ZoneShape = 'polygon' | 'circle';

/**
 * コースタイプ
 * - circuit : 周回コース（スタート地点を繰り返し通過）
 * - street  : ストリート/峠（一方通行→折り返し自動検知）
 * - unknown : 判定不能（境界やゴール未設定）
 */
export type CourseType = 'circuit' | 'street' | 'unknown';

/**
 * スコアリングゾーン — コース内の特定エリアでスコア倍率が変わる
 *
 * zoneShape === 'polygon' : polygon 配列で形状を定義
 * zoneShape === 'circle'  : center + radius で形状を定義（コーナーに最適）
 */
export type ScoringZone = {
  id: string;
  name: string;
  zoneShape: ZoneShape;
  /** ポリゴン形状の頂点列 (zoneShape === 'polygon' 時に使用) */
  polygon: GeoPoint[];
  /** 円形の中心座標 (zoneShape === 'circle' 時に使用) */
  center?: GeoPoint;
  /** 円形の半径 (m) (zoneShape === 'circle' 時に使用) */
  radius?: number;
  /** このゾーン内でのスコア倍率 (1.0〜3.0) */
  multiplier: number;
  /** ゾーン色 (hex, 例: '#FF4444') */
  color: string;

  // ── コリドー（廊下型）ゾーン用メタデータ ──
  // AI 検知コーナーから生成されたゾーンの調整に使用
  /** コリドーの脊椎パス（元の GPS 点列） */
  corridorPath?: GeoPoint[];
  /** 現在の片側幅 (m) */
  corridorHalfWidth?: number;
  /** 脊椎パスの使用開始インデックス（デフォルト: 0） */
  corridorStartIdx?: number;
  /** 脊椎パスの使用終了インデックス（デフォルト: length-1） */
  corridorEndIdx?: number;

  // ── クリップライン（AI 自動生成） ──
  /** イン / アウトクリップ種別 */
  clipType?: 'inside' | 'outside';
  /** AI 推奨ラインか */
  recommendedClip?: boolean;
  /** 旋回方向 */
  turnDirection?: 'left' | 'right';
  /** 推奨理由（UI 表示用） */
  clipReason?: string;

  /** このゾーン（コーナー）でのベスト記録 */
  bestRecord?: ZoneBestRecord;
};

/** スコアリングゾーンごとのベスト記録 */
export type ZoneBestRecord = {
  /** 最高スリップアングル (°) */
  bestAngleDeg: number;
  /** 最高ピーク横 G */
  bestPeakG: number;
  /** このゾーン内ドリフトの最高獲得 pt（ゾーン倍率込み） */
  bestPoints: number;
  /** 記録更新日時 (ISO 8601) */
  updatedAt?: string;
};

/**
 * コース別スコアリングプロファイル
 *
 * コースの特性（速度域・コーナー角・傾斜・難易度）に合わせて
 * 採点パラメータをチューニングする。
 *
 * AI 自動生成 → ユーザーが手動調整 のフローで使用。
 */
export type ScoringProfile = {
  /**
   * 速度ボーナスの参照速度 (km/h)。
   * この速度に達すると speedBonus が 2.0× になる。
   * 峠 → 40–60, 一般サーキット → 80, 高速コース → 120
   */
  speedReferenceKmh: number;

  /**
   * スリップアングルボーナスの飽和角度 (°)。
   * この角度でボーナスが最大 (1.5×) に達する。
   * タイトヘアピン → 45, 通常コーナー → 90, 高速コーナー → 120
   */
  angleScaleDeg: number;

  /**
   * コンボチェーンの有効時間 (ms)。
   * コーナーが連続するコース → 短く (2000), コーナー間の直線が長い → 長く (5000)
   */
  comboWindowMs: number;

  /**
   * 傾斜補正係数 (0.5〜1.0)。
   * 急坂では重力成分が横Gに混入するためスコアを下補正する。
   * 平坦 → 1.0, 緩い坂 → 0.85, 急坂 → 0.70
   */
  gradientCompensation: number;

  /**
   * グレード難易度。
   * - easy   : S≥4000 / A≥2500 / B≥1200 / C≥400
   * - normal : S≥8000 / A≥5000 / B≥2500 / C≥800  (デフォルト)
   * - hard   : S≥12000 / A≥8000 / B≥4000 / C≥1500
   * - pro    : S≥20000 / A≥13000 / B≥7000 / C≥3000
   */
  gradeDifficulty: 'easy' | 'normal' | 'hard' | 'pro';
};

/** AI が自動生成するデフォルトのスコアリングプロファイル */
export const DEFAULT_SCORING_PROFILE: ScoringProfile = {
  speedReferenceKmh:    80,
  angleScaleDeg:        90,
  comboWindowMs:        3000,
  gradientCompensation: 1.0,
  gradeDifficulty:      'normal',
};

/** 保存済みドリフトコース */
export type Course = {
  id: string;
  name: string;
  /** コース走行エリアの境界ポリゴン */
  boundary: GeoPoint[];
  /** スタートトリガー地点 */
  startPoint: GeoPoint;
  /** スタートトリガー半径 (m) — この円内に入ると自動スタート候補になる */
  startRadius: number;
  /** ゴール地点（省略可） */
  endPoint?: GeoPoint;
  /** ゴール判定半径 (m) */
  endRadius?: number;
  /** コース内のスコアリングゾーン */
  scoringZones: ScoringZone[];
  /** 保存日時 (ISO 8601) */
  savedAt: string;
  /** 最終走行日時 */
  lastUsedAt?: string;
  /** このコースでの最高スコア */
  bestScore?: number;
  /**
   * コースタイプ（保存時に AI 判定・手動上書き可）
   * undefined の場合は読み込み時に detectCourseType() で自動判定
   */
  courseType?: CourseType;

  /**
   * コース別スコアリングプロファイル（AI 自動生成 → 手動調整可）
   * undefined の場合は DEFAULT_SCORING_PROFILE を使用
   */
  scoringProfile?: ScoringProfile;

  /**
   * 採点スタイルプリセット ID（Phase 2: 自動生成ウィザードで設定）
   * undefined の場合はプリセットなし（AI プロファイルのみ）
   */
  competitionPresetId?: string;

  /**
   * 自動生成フラグ（ウィザードで生成されたコース）
   * undefined / false の場合は手動作成
   */
  autoGenerated?: boolean;
};
